### ISSUE TITLE
[FEATURE] Add support for scala spark_jar_task in dbx datafactory reflect

### ISSUE THREAD

**Issue by KrzysztofDobosz** [databrickslabs/dbx#103]
## Expected Behavior
According to the docs (and the code), currently only spark_python_task is supported in dbx datafactory reflect command. Scala jars are already supported for deployment and updating Jar activity in a similar way should be easy to implement.
## Current Behavior
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\SPA\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\SPA\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\SPA\Scripts\dbx.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\envs\SPA\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\SPA\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Anaconda3\envs\SPA\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\Anaconda3\envs\SPA\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\Anaconda3\envs\SPA\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Anaconda3\envs\SPA\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\SPA\lib\site-packages\dbx\commands\datafactory.py", line 70, in reflect
    reflector.launch()
  File "C:\ProgramData\Anaconda3\envs\SPA\lib\site-packages\dbx\commands\datafactory.py", line 230, in launch
    job_activity = self._generate_activity(job_spec, service_name)
  File "C:\ProgramData\Anaconda3\envs\SPA\lib\site-packages\dbx\commands\datafactory.py", line 188, in _generate_activity
    python_file=job_spec.get("spark_python_task").get("python_file"),
AttributeError: 'NoneType' object has no attribute 'get'
```
## Steps to Reproduce (for bugs)
Run `dbx datafactory reflect` on job defined here: [https://github.com/renardeinside/dbx-scala-example](url)

* dbx version used: 0.2.1
* Databricks Runtime version: 9.1

**Comment by renardeinside** [comment]
added in #108 , will be released in 0.2.2
