### ISSUE TITLE
ImportError: Bad git executable.

### ISSUE THREAD

**Issue by justinTM** [databrickslabs/dbx#187]
## Expected Behavior
`dbx --version` shows currently-installed version of the `dbx` CLI.

## Current Behavior
Command fails with the following:
```console
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/git/__init__.py", line 87, in <module>
    refresh()
  File "/usr/local/lib/python3.8/dist-packages/git/__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
  File "/usr/local/lib/python3.8/dist-packages/git/cmd.py", line 341, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/dbx", line 5, in <module>
    from dbx.cli import cli
  File "/usr/local/lib/python3.8/dist-packages/dbx/cli.py", line 4, in <module>
    from dbx.commands.configure import configure
  File "/usr/local/lib/python3.8/dist-packages/dbx/commands/configure.py", line 7, in <module>
    from dbx.utils.common import (
  File "/usr/local/lib/python3.8/dist-packages/dbx/utils/common.py", line 12, in <module>
    import git
  File "/usr/local/lib/python3.8/dist-packages/git/__init__.py", line 89, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
```
## Steps to Reproduce (for bugs)
```dockerfile
FROM ubuntu:20.04
RUN apt-get update

# install python package manager
RUN apt-get -y install python3-pip
RUN pip3 --version

# install python packages
RUN pip3 install dbx --no-cache
RUN dbx --version
```

## Your Environment

* dbx version used:
* Databricks Runtime version:

**Comment by justinTM** [comment]
FROM python:3.10

fixed:

```dockerfile
# set databricks-cli environment variables
ENV DATABRICKS_HOST=value
ENV DATABRICKS_TOKEN=value

# install databricks command line interface
RUN pip install --upgrade databricks-cli
RUN databricks --version

# install databricks cli extensions
RUN pip install --upgrade dbx
RUN dbx --version
```
