### ISSUE TITLE
No module named 'azure.core.rest'

### ISSUE THREAD

**Issue by rfcortes** [databrickslabs/dbx#192]
Hello,

After upgrading dbx to version 0.4.1 I'm getting the following error on the cli

```
 dbx
Traceback (most recent call last):
  File "/Users/machine/.pyenv/versions/3.8.0/bin/dbx", line 5, in <module>
    from dbx.cli import cli
  File "/Users/machine/.pyenv/versions/3.8.0/lib/python3.8/site-packages/dbx/cli.py", line 8, in <module>
    from dbx.commands.datafactory import datafactory
  File "/Users/machine/.pyenv/versions/3.8.0/lib/python3.8/site-packages/dbx/commands/datafactory.py", line 9, in <module>
    from azure.mgmt.datafactory import DataFactoryManagementClient
  File "/Users/machine/.pyenv/versions/3.8.0/lib/python3.8/site-packages/azure/mgmt/datafactory/__init__.py", line 9, in <module>
    from ._data_factory_management_client import DataFactoryManagementClient
  File "/Users/machine/.pyenv/versions/3.8.0/lib/python3.8/site-packages/azure/mgmt/datafactory/_data_factory_management_client.py", line 12, in <module>
    from azure.core.rest import HttpRequest, HttpResponse
ModuleNotFoundError: No module named 'azure.core.rest'
```
I tried to reinstall azure-core package, but I did not solve the issue

Do you have any information about this issue?

dbx==0.4.1
databricks-cli==0.16.5

Thanks !

**Comment by rfcortes** [comment]
solved after upgrading azure-core to v1.23.0
