### ISSUE TITLE
File already exist, cannot overwrite during `dbx deploy`

### ISSUE THREAD

**Issue by naziakhan-drizly** [databrickslabs/dbx#202]
## Expected Behavior
Deploy a job using `dbx deploy`

## Current Behavior
During `dbx deploy` I get error `File already exists, cannot overwrite: &apos;/dbx/production/e515d51b8e2049ac8f77147165e1acef/artifacts/job_folder/entrypoint.py&apos;</pre></p>`

## Context
I am trying to deploy my job using command `dbx deploy` in databricks environment. The error message says the entrypoint.py already exists, but I am not sure why because every time I would run `dbx deploy`, it would create a new experiment id which doesn’t interfere with the previous experiments.
I also tried deleting the artifact entrypoint.py and run `dbx deploy` in my terminal in databricks environment again and it gave same error.
Following is the error 
```
[dbx]Traceback (most recent call last):
  File "/opt/miniconda3/envs/databricks/bin/dbx", line 8, in <module>
    sys.exit(cli())
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/dbx/commands/deploy.py", line 162, in deploy
    adjust_job_definitions(deployment["jobs"], dependency_manager, _file_uploader, api_client)
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/dbx/utils/adjuster.py", line 53, in adjust_job_definitions
    walk_content(adjustment_callback, workload_reference)
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/dbx/utils/adjuster.py", line 59, in walk_content
    walk_content(func, item, content, key)
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/dbx/utils/adjuster.py", line 59, in walk_content
    walk_content(func, item, content, key)
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/dbx/utils/adjuster.py", line 64, in walk_content
    parent[index] = func(content)
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/dbx/utils/adjuster.py", line 18, in adjustment_callback
    return adjust_path(p, file_uploader)
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/dbx/utils/adjuster.py", line 117, in adjust_path
    adjusted_path = _non_strict_path_adjustment(candidate, file_uploader)
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/dbx/utils/adjuster.py", line 101, in _non_strict_path_adjustment
    adjusted_path = file_uploader.upload_and_provide_path(file_path)
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/dbx/utils/common.py", line 452, in upload_and_provide_path
    self._upload_file(local_path)
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/dbx/utils/common.py", line 445, in _upload_file
    mlflow.log_artifact(str(file_path), str(posix_path.parent))
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 606, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/mlflow/tracking/client.py", line 955, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 355, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/mlflow/store/artifact/dbfs_artifact_repo.py", line 119, in log_artifact
    self._databricks_api_request(
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/mlflow/store/artifact/dbfs_artifact_repo.py", line 61, in _databricks_api_request
    return http_request_safe(host_creds=host_creds, endpoint=endpoint, method=method, **kwargs)
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 162, in http_request_safe
    return verify_rest_response(response, endpoint)
  File "/opt/miniconda3/envs/databricks/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 175, in verify_rest_response
    raise MlflowException("%s. Response body: '%s'" % (base_msg, response.text))
mlflow.exceptions.MlflowException: API request to endpoint /dbfs/dbx/production/e515d51b8e2049ac8f77147165e1acef/artifacts/job_folder/entrypoint.py failed with error code 409 != 200. Response body: '<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 409 </title>
</head>
<body>
<h2>HTTP ERROR: 409</h2>
<p>Problem accessing /dbfs/dbx/production/e515d51b8e2049ac8f77147165e1acef/artifacts/job_folder/entrypoint.py. Reason:
<pre>    File already exists, cannot overwrite: &apos;/dbx/production/e515d51b8e2049ac8f77147165e1acef/artifacts/job_folder/entrypoint.py&apos;</pre></p>
<hr />
</body>
</html>
```

## Your Environment

* dbx version used:  0.4.1
* Databricks Runtime version: 0.16.4

**Comment by renardeinside** [comment]
hi @naziakhan-drizly , 
could you please try using the strict path adjustment policy as described [here](https://dbx.readthedocs.io/en/latest/path_adjustment.html)?

**Comment by naziakhan-drizly** [comment]
@renardeinside, this works!
