### ISSUE TITLE
[BUG] auto discovery for *.y[a]ml.j2 not working

### ISSUE THREAD

**Issue by teaVeloper** [databrickslabs/dbx#229]
Minor Bug, but i want to report it, as the documentations states different

## Expected Behavior
Auto Discovery for file conf/deployment.yml.j2
as documented https://dbx.readthedocs.io/en/latest/jinja2_support.html

## Current Behavior
no auto discovery - need to supply the file with --deployment-file flag for dbx execute or dbx deploy commands

## Steps to Reproduce (for bugs)
rename conf/deployment.yml to conf/deployment.yml.j2 (maybe use some jinja syntax in there, but no need)
(i also tried conf/deployment.yaml.j2)
```
❯ dbx execute --job databricks-job-test --cluster-id $CLUSTER_ID --requirements-file re.txt --no-rebuild

[dbx][2022-05-09 18:23:36.545] No environment variables provided, using the ~/.databrickscfg
[dbx][2022-05-09 18:23:39.079] Executing job: databricks-job-test in environment default on cluster None (id: $CLUSTER_ID)
[dbx][2022-05-09 18:23:39.080] No rebuild will be done, please ensure that the package distribution is in dist folder
Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/databricks-job-r2ngUSF2-py3.8/bin/dbx", line 8, in <module>
    sys.exit(cli())
  File "/home/user/.cache/pypoetry/virtualenvs/databricks-job-r2ngUSF2-py3.8/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/databricks-job-r2ngUSF2-py3.8/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/user/.cache/pypoetry/virtualenvs/databricks-job-r2ngUSF2-py3.8/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.cache/pypoetry/virtualenvs/databricks-job-r2ngUSF2-py3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.cache/pypoetry/virtualenvs/databricks-job-r2ngUSF2-py3.8/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/databricks-job-r2ngUSF2-py3.8/lib/python3.8/site-packages/dbx/commands/execute.py", line 90, in execute
    deployment_file = finalize_deployment_file_path(deployment_file)
  File "/home/user/.cache/pypoetry/virtualenvs/databricks-job-r2ngUSF2-py3.8/lib/python3.8/site-packages/dbx/commands/deploy.py", line 262, in finalize_deployment_file_path
    raise Exception(
Exception: Auto-discovery was unable to find any deployment file in the conf directory. Please provide file name via --deployment-file option
```
```
❯ dbx deploy --job databricks-job --requirements-file re.txt --no-rebuild 
```
produces the almost same Traceback
just the line with ../execute.py is different referencing to line 136 in deploy.py

## Context
I tried out to shift from yaml files to j2 templates and noticed auto discovery is not working anymore - as the documentation states that it works i want to report it as bug.

## Your Environment
Ubuntu 20.04.4
dbx 0.4.1
running inside poetry managed venv

* dbx version used: 0.4.1
* Databricks Runtime version: *any

**Comment by mitchstockdale** [comment]
The latest release (0.4.1) does not include the [PR](https://github.com/databrickslabs/dbx/pull/184) addressing this.

**Comment by renardeinside** [comment]
thanks, @mitchstockdale!
This issue will be release in 0.5.0, planned release date is 17th of May .
