### ISSUE TITLE
dbx deploy parsing `requirements.txt` wrong

### ISSUE THREAD

**Issue by teaVeloper** [databrickslabs/dbx#251]
## Expected Behavior
Using dbx deploy with a "valid" (for vanilla pip) `requirements.txt` file to parse it in a way databricks can work with it.

## Current Behavior
tl;dr: incomplete sanitizing of `requirements-file` before parsing for Jobs API

Parsing extra content which is valid for a `requirements.txt` but causes databricks to break, as dbx parses it as a package. Also databricks fails on windows only dependencies, as it seems to not be able to resolve those, while pip just ignores these on another platform.
https://github.com/databrickslabs/dbx/blob/main/dbx/utils/dependency_manager.py#L56

## Steps to Reproduce (for bugs)
Minimal working example inside a `requirements-file`:

```requirements.txt
--extra-index-url https://url-to-private-pypi
ruamel.yaml.clib==0.2.6; python_version >= "3.5"
win32-setctime==1.1.0; python_version >= "3.7" and python_version < "4.0" and sys_platform == "win32"
```
this will parse the following job.json (copied from the WebUI's JSON View):

```job.json
... omitted ...
        "libraries": [
            {
                "pypi": {
                    "package": "--extra-index-url https://url-to-private-pypi"
                }
            },
           {
                "pypi": {
                    "package": "ruamel.yaml.clib==0.2.6; python_version >= \"3.5\""
                }
            },
            {
                "pypi": {
                    "package": "win32-setctime==1.1.0; python_version >= \"3.7\" and python_version < \"4.0\" and sys_platform == \"win32\""
                }
            }
]
.. omitted ...
```
which is obviously wrong!
Also databricks will fail with the `sys_platform == win32` only.

## Context

I manage my project with `poetry` and create a `requirements.txt` dynamically for pushing it to databricks using dbx. My deployments thus fail, as these are parsed in the wrong way.

dbx execute using the same `requirements.txt` works fine, as it uses `%pip` in the background. I use dbx execute for testing and CI before running the deployment. 
https://github.com/databrickslabs/dbx/blob/v0.4.1/dbx/commands/execute.py#L130
Maybe there might also be a solution to use `%pip` for deployments?

## Your Environment
Ubuntu 20.04.4 LTS x86_64
running inside a poetry managed venv

* dbx version used: 0.4.1
* Databricks Runtime version: 10.3 ML (includes Apache Spark 3.2.1, Scala 2.12)

**Comment by renardeinside** [comment]
Hi @teaVeloper , 
this is fixed in #287 , will be released in 0.6.0, Thanks a lot for reporting this issue!

**Comment by pstanisl** [comment]
I am facing a similar issue.

My DBX version

```bash
$ dbx --version
DataBricks eXtensions aka dbx, version ~> 0.6.8
```

My deployment file

```yaml
custom:
  basic-cluster-props: &basic-cluster-props
    spark_version: "10.4 LTS"
    node_type_id: "Standard_E4a_v4"

  basic-static-cluster: &basic-static-cluster
    new_cluster:
      <<: *basic-cluster-props
      num_workers: 4

environments:
  default:
    jobs:
      - name: "feature-engineering"
        spark_python_task:
          python_file: "file://notebooks/run.py"
      - name: "feature-engineering-repo"
        <<: *basic-static-cluster
        deployment_config:
          no_package: true
        notebook_task:
          notebook_path: "/Repos/some/path/to/notebooks/run"
```

My `requirements.txt` file

```python
--extra-index-url https://url-to-private-pypile

aiobotocore==2.1.2; python_version >= "3.6"
...
```

Command:

```bash
$ dbx deploy --deployment-file conf/o2/deployment.yml --job feature-engineering-repo --no-rebuild --no-package
[dbx][2022-07-25 14:16:44.723] Starting new deployment for environment default
[dbx][2022-07-25 14:16:44.725] Using profile provided from the project file
[dbx][2022-07-25 14:16:44.725] Found auth config from provider ProfileEnvConfigProvider, verifying it
[dbx][2022-07-25 14:16:44.725] Found auth config from provider ProfileEnvConfigProvider, verification successful
[dbx][2022-07-25 14:16:44.725] Profile aicentre-dev will be used for deployment
[dbx][2022-07-25 14:16:45.659] Using the provided deployment file conf/o2/deployment.yml
[dbx][2022-07-25 14:16:45.664] Deployment will be performed only for the following jobs: ['feature-engineering-repo']
[dbx][2022-07-25 14:16:45.664] No rebuild will be done, please ensure that the package distribution is in dist folder
[dbx][2022-07-25 14:16:45.664] Locating package file
[dbx][2022-07-25 14:16:45.664] Package file located in: dist/urm_feature_engineering-1.2.0-py3-none-any.whl
[dbx][2022-07-25 14:16:45.664] No package definition will be added into any jobs in the given deployment
Traceback (most recent call last):
  File "/Users/pstanisl/repos/o2/urm/feature-engineering/.venv/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/Users/pstanisl/repos/o2/urm/feature-engineering/.venv/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing/core.py", line 1143, in parse_string
    raise exc.with_traceback(None)
pkg_resources._vendor.pyparsing.exceptions.ParseException: Expected W:(0-9A-Za-z), found '-'  (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pstanisl/repos/o2/urm/feature-engineering/.venv/bin/dbx", line 8, in <module>
    sys.exit(cli())
  File "/Users/pstanisl/repos/o2/urm/feature-engineering/.venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pstanisl/repos/o2/urm/feature-engineering/.venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/pstanisl/repos/o2/urm/feature-engineering/.venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/pstanisl/repos/o2/urm/feature-engineering/.venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pstanisl/repos/o2/urm/feature-engineering/.venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/pstanisl/repos/o2/urm/feature-engineering/.venv/lib/python3.8/site-packages/dbx/commands/deploy.py", line 171, in deploy
    dependency_manager = DependencyManager(no_package, no_rebuild, requirements_file)
  File "/Users/pstanisl/repos/o2/urm/feature-engineering/.venv/lib/python3.8/site-packages/dbx/utils/dependency_manager.py", line 26, in __init__
    self._requirements_references: List[LibraryReference] = self._get_requirements_from_file(requirements_file)
  File "/Users/pstanisl/repos/o2/urm/feature-engineering/.venv/lib/python3.8/site-packages/dbx/utils/dependency_manager.py", line 53, in _get_requirements_from_file
    filtered_libraries = self._delete_managed_libraries(requirements_content)
  File "/Users/pstanisl/repos/o2/urm/feature-engineering/.venv/lib/python3.8/site-packages/dbx/utils/dependency_manager.py", line 32, in _delete_managed_libraries
    for package in packages:
  File "/Users/pstanisl/repos/o2/urm/feature-engineering/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3102, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/Users/pstanisl/repos/o2/urm/feature-engineering/.venv/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 104, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'--extra-'": Expected W:(0-9A-Za-z)
```

**Comment by renardeinside** [comment]
hi @pstanisl , 
`--requirements-file` functionality is deprecated. Please use standard `setup.py`-based dependency provisioning. 
The case with --extra-intex-url is described [here](https://stackoverflow.com/questions/24443583/using-an-extra-python-package-index-url-with-setup-py) and [here](https://setuptools.pypa.io/en/latest/setuptools.html#new-and-changed-setup-keywords).

**Comment by pstanisl** [comment]
Hi @renardeinside.

Thank you for your answer. But, as far as I know, support for `dependency_links` in `setup.py` was dropped by `pip`; see [here](https://setuptools.pypa.io/en/latest/deprecated/dependency_links.html?highlight=dependency_links). Proposed solution is to use PEP 508 as mentioned [here](https://stackoverflow.com/a/54793503), but it does not work for me. It fails with an error

```bash
'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at "'@ https:'": Expected string_end
```

Also, it is a bit problematic to automate it because I manage dependencies with `poetry` and for the build. Poetry is able to generate `requirements.txt` with `--extra-index-url` and it is working for `dbx execute` but not for `dbx deploy`. 

I can use the `setup.py` for build by DBX, but I still do not know the working solution for a custom PyPI index with authentication.

**Comment by renardeinside** [comment]
hi @pstanisl , 
if you're using poetry, it will automatically add all dependency descriptions into the .whl package. 
Here is how your pipeline could look like. Imagine having a repository with following structure:

```
.
├── Makefile
├── README.rst
├── conf
│   └── deployment.yml
├── dbx_poetry_example
│   ├── __init__.py
│   └── entrypoint.py
├── dist
│   └── dbx_poetry_example-0.1.0-py3-none-any.whl
├── poetry.lock
├── pyproject.toml
└── tests
    ├── __init__.py
    └── test_dbx_poetry_example.py
```
As you can see I'm using `poetry` and `dbx` together here. There is no requirements.txt or setup.py file provided. 

Second, I add a new dependency to my `pyproject.toml` file:
```
poetry add "fastapi[all]"
```

I also add a secondary repository to my `pyproject.toml` file, so in the end it looks like this:
```
[tool.poetry]
name = "dbx-poetry-example"
version = "0.1.0"
description = ""
authors = ["renardeinside <polarpersonal@gmail.com>"]

[[tool.poetry.source]]
name = "secondary"
url = "https://pypi.org/simple/"
secondary = true

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
fastapi = {extras = ["all"], version = "^0.79.0"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

With this, I can use standard poetry tools to build a package:
```
rm -rf dist/* # to cleanup the dist folder
poetry build -f wheel
```
This command will produce a dist/*.whl file which is my package. With this I can execute my code via execute:
```
rm -rf dist/*
	poetry build -f wheel
	dbx execute --job=dbx-poetry-example --task=first-task --cluster-name=<some-cluster-name> --no-rebuild
``` 

Please note the `--no-rebuild` option - it disables the standard pip-based build (we don't need it since `poetry` does the packaging already.

When running this code via `dbx execute`, it will properly install and resolve the package dependencies provided from poetry. dev-dependencies won't be installed. 

Now to the topic of configuring the access to the custom pypi repository - you'll need to add an init script which configures the `pip.conf` file as described for instance in [this blogpost](https://polarpersonal.medium.com/releasing-and-using-python-packages-with-azure-devops-and-azure-databricks-906ec2ff8e2d).

**Comment by pstanisl** [comment]
Hi @renardeinside.

Thank you for your answer. I did not realize the option to define the init script. It worked. Thank you very much.
