### ISSUE TITLE
dbx sync doesn't work when run inside of docker

### ISSUE THREAD

**Issue by fjakobs** [databrickslabs/dbx#252]
## Expected Behavior

`dbx sync` works the same way inside and outside of a container. This is a big problem since I'm using dbx from VSCode remote extensions.

## Current Behavior

Running `dbx sync` from inside of a container throws this error:

```
$ dbx  sync repo --profile AWS-DOGFOOD -d notebook-best-practics -i covid_analysis -i notebooks -i tests -ip 'requirements*' --user fabian.jakobs@databricks.com --full-sync
[dbx][2022-05-19 15:06:46.265] Syncing from /workspaces/notebook-best-practices
[dbx][2022-05-19 15:06:46.272] Target base path: /Repos/fabian.jakobs@databricks.com/notebook-best-practics
[dbx][2022-05-19 15:06:46.273] Ignoring patterns from /workspaces/notebook-best-practices/.gitignore
[dbx][2022-05-19 15:06:46.308] Performing a full sync
[dbx][2022-05-19 15:06:46.309] Starting initial copy
[dbx][2022-05-19 15:06:46.338] Checking if any unmatched files/directories would be deleted
[dbx][2022-05-19 15:06:46.343] Creating /Repos/fabian.jakobs@databricks.com/notebook-best-practics/covid_analysis
[dbx][2022-05-19 15:06:46.352] Creating /Repos/fabian.jakobs@databricks.com/notebook-best-practics/notebooks
[dbx][2022-05-19 15:06:46.355] Creating /Repos/fabian.jakobs@databricks.com/notebook-best-practics/tests
[dbx][2022-05-19 15:06:47.202] Putting /Repos/fabian.jakobs@databricks.com/notebook-best-practics/covid_analysis/transforms.py
[dbx][2022-05-19 15:06:47.221] Putting /Repos/fabian.jakobs@databricks.com/notebook-best-practics/notebooks/covid_eda_modular.py
[dbx][2022-05-19 15:06:47.235] Putting /Repos/fabian.jakobs@databricks.com/notebook-best-practics/notebooks/covid_eda_raw.py
[dbx][2022-05-19 15:06:47.243] Putting /Repos/fabian.jakobs@databricks.com/notebook-best-practics/notebooks/run_unit_tests.py
[dbx][2022-05-19 15:06:47.253] Putting /Repos/fabian.jakobs@databricks.com/notebook-best-practics/requirements-dbr-10.4.txt
[dbx][2022-05-19 15:06:47.260] Putting /Repos/fabian.jakobs@databricks.com/notebook-best-practics/requirements-dev.txt
[dbx][2022-05-19 15:06:47.265] Putting /Repos/fabian.jakobs@databricks.com/notebook-best-practics/requirements.txt
[dbx][2022-05-19 15:06:47.269] Putting /Repos/fabian.jakobs@databricks.com/notebook-best-practics/tests/transforms_test.py
[dbx][2022-05-19 15:06:48.992] Done. Watching for changes...
Traceback (most recent call last):
  File "/usr/local/bin/dbx", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dbx/commands/sync.py", line 383, in repo
    main_loop(
  File "/usr/local/lib/python3.8/dist-packages/dbx/commands/sync.py", line 116, in main_loop
    with file_watcher(source=source, matcher=matcher) as event_handler:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/dist-packages/dbx/sync/event_handler.py", line 83, in file_watcher
    observer.start()
  File "/usr/local/lib/python3.8/dist-packages/watchdog/observers/api.py", line 262, in start
    emitter.start()
  File "/usr/local/lib/python3.8/dist-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/usr/local/lib/python3.8/dist-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/usr/local/lib/python3.8/dist-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/usr/local/lib/python3.8/dist-packages/watchdog/observers/inotify_c.py", line 155, in __init__
    Inotify._raise_error()
  File "/usr/local/lib/python3.8/dist-packages/watchdog/observers/inotify_c.py", line 404, in _raise_error
    raise OSError(err, os.strerror(err))
OSError: [Errno 38] Function not implemented
```

## Steps to Reproduce (for bugs)

Just run `dbx sync` from inside of a container.

## Your Environment

* dbx version used: latest version on main

**Comment by fjakobs** [comment]
@matthayes can you take a look? I believe this is an issue with watchdog.

**Comment by fjakobs** [comment]
I narrowed it down a little:

Doesn't work:
  - Docker image mcr.microsoft.com/vscode/devcontainers/base:ubuntu-20.04
  - x86 docker image running on ARM (M1) Mac with CPU emulation

Does work:
  - Docker image mcr.microsoft.com/vscode/devcontainers/python:0-3.10-bullseye (Debian)
  - ARM docker image running on ARM Mac

**Comment by fjakobs** [comment]
The polling observer does fix the issue https://github.com/matthayes/dbx/commit/f8b692550c34509873cfb42ad927f3f2cffdd817

**Comment by matthayes** [comment]
Thanks for the additional details!  It worked for me when I tried using the VsCode container.  I'm using an x86 Mac, so this probably explains the difference.  I'll work on preparing a PR for the fallback approach so that the tool can still work if this situation does arise.

**Comment by matthayes** [comment]
@fjakobs can we close this now?

**Comment by fjakobs** [comment]
Yes, this is resolved. Thanks
