### ISSUE TITLE
dbx configure fails

### ISSUE THREAD

**Issue by rleung-dataai** [databrickslabs/dbx#265]
## Expected Behavior
From https://dbx.readthedocs.io/en/latest/quickstart.html, I would expect the simple command of `dbx configure --profile=test` would work. 

## Current Behavior
Running `dbx configure --profile=test` now gives 

```
Traceback (most recent call last):                                                                                        │    _message.Message._CheckCalledFromGeneratedFile()
  File "/opt/homebrew/bin/dbx", line 5, in <module>                                                                       │TypeError: Descriptors cannot not be created directly.
    from dbx.cli import cli                                                                                               │If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
  File "/opt/homebrew/lib/python3.9/site-packages/dbx/cli.py", line 4, in <module>                                        │If you cannot immediately regenerate your protos, some other possible workarounds are:
    from dbx.commands.configure import configure                                                                          │ 1. Downgrade the protobuf package to 3.20.x or lower.
  File "/opt/homebrew/lib/python3.9/site-packages/dbx/commands/configure.py", line 7, in <module>                         │ 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
    from dbx.utils.common import (                                                                                        │
  File "/opt/homebrew/lib/python3.9/site-packages/dbx/utils/common.py", line 14, in <module>                              │More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
    import mlflow                                                                                                         │rleung@DAAMERRLEUNG gummybear %
  File "/opt/homebrew/lib/python3.9/site-packages/mlflow/__init__.py", line 32, in <module>                               │
    import mlflow.tracking._model_registry.fluent                                                                         │
  File "/opt/homebrew/lib/python3.9/site-packages/mlflow/tracking/__init__.py", line 8, in <module>                       │
    from mlflow.tracking.client import MlflowClient                                                                       │
  File "/opt/homebrew/lib/python3.9/site-packages/mlflow/tracking/client.py", line 16, in <module>                        │
    from mlflow.entities import Experiment, Run, RunInfo, Param, Metric, RunTag, FileInfo, ViewType                       │
  File "/opt/homebrew/lib/python3.9/site-packages/mlflow/entities/__init__.py", line 6, in <module>                       │
    from mlflow.entities.experiment import Experiment                                                                     │
  File "/opt/homebrew/lib/python3.9/site-packages/mlflow/entities/experiment.py", line 2, in <module>                     │
    from mlflow.entities.experiment_tag import ExperimentTag                                                              │
  File "/opt/homebrew/lib/python3.9/site-packages/mlflow/entities/experiment_tag.py", line 2, in <module>                 │
    from mlflow.protos.service_pb2 import ExperimentTag as ProtoExperimentTag                                             │
  File "/opt/homebrew/lib/python3.9/site-packages/mlflow/protos/service_pb2.py", line 18, in <module>                     │
    from .scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2                                                          │
  File "/opt/homebrew/lib/python3.9/site-packages/mlflow/protos/scalapb/scalapb_pb2.py", line 29, in <module>             │
    options = _descriptor.FieldDescriptor(                                                                                │
  File "/opt/homebrew/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__                    │
    _message.Message._CheckCalledFromGeneratedFile()                                                                      │
TypeError: Descriptors cannot not be created directly.                                                                    │
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.  │
If you cannot immediately regenerate your protos, some other possible workarounds are:                                    │
 1. Downgrade the protobuf package to 3.20.x or lower.                                                                    │
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).    │
                                                                                                                          │
More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates## Steps to Reproduce (for bugs)
```

Indeed, it seems to me typing `dbx <anything here>` doesn't work and gives the same crash. 

## Context
This seems to be related to the issue discussed [here](https://github.com/protocolbuffers/protobuf/issues/10051).

## Your Environment

* dbx version used: Running `dbx --version` also returns the above crash. 
* Databricks Runtime version: 9.1 LTS

**Comment by matthayes** [comment]
See here: https://github.com/databrickslabs/dbx/issues/262#issuecomment-1138229736
