### ISSUE TITLE
"dbx launch --run-as-submit" fails is requirements.txt has comments

### ISSUE THREAD

**Issue by fjakobs** [databrickslabs/dbx#286]
## Expected Behavior

Comments (everything after "#") in requirements files should be irgnored.

## Current Behavior

When running `dbx launch` with a requirements.txt that contains a comment it fails with this error:

```
  [dbx][2022-06-14 16:24:05.779] [Run Id: 634841118601831] Current run status info - result state: FAILED, lifecycle state: INTERNAL_ERROR, state message: Library installation failed for library due to user error for pypi {
    package: "# Additional cluster packages go here"
  }
  . Error messages:
  Library installation attempted on the driver node of cluster 0614-162033-rck3t7lz and failed. Please refer to the following error message to fix the library or contact Databricks support. Error Code: DRIVER_LIBRARY_INSTALLATION_FAILURE. Error Message: org.apache.spark.SparkException: Process List(/databricks/python/bin/pip, install, # Additional cluster packages go here, --disable-pip-version-check) exited with code 1. ERROR: Invalid requirement: '# Additional cluster packages go here'
  [dbx][2022-06-14 16:24:05.779] Finished tracing run with id 634841118601831
  
  Traceback (most recent call last):
    File "/usr/local/bin/dbx", line 8, in <module>
      sys.exit(cli())
    File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
  
      return self.main(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
      rv = self.invoke(ctx)
    File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
  
      return __callback(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/dbx/commands/launch.py", line 168, in launch
      raise Exception("Tracked run failed during execution. Please check Databricks UI for run logs")
  Exception: Tracked run failed during execution. Please check Databricks UI for run logs
```

## Steps to Reproduce (for bugs)

1. create a dbx project
2. add a comment to `requirements.txt`
3. run `dbx launch --job=<JOB_NAME> --as-run-submit --trace`

## Your Environment

* dbx version used: 0.5.0
* Databricks Runtime version: 10.4

**Comment by fjakobs** [comment]
Bug is here https://github.com/databrickslabs/dbx/blob/main/dbx/utils/dependency_manager.py#L50
