### ISSUE TITLE
dbx v0.6+ error with dbx deploy :  'Invalid python file URI: cicd_test/tasks/first/entrypoint.py. '

### ISSUE THREAD

**Issue by copdips** [databrickslabs/dbx#309]
## Expected Behavior

No error with `dbx deploy`  (dbx v0.6+)

## Current Behavior

`only for dbx v0.6+`

Error thrown: 

```log
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/databricks_cli/sdk/api_client.py", line 138, in perform_query
    resp.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://adb-111111111111.11..azuredatabricks.net/api/2.0/jobs/reset

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.13/x64/bin/dbx", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/dbx/commands/deploy.py", line 162, in deploy
    deployment_data = _create_jobs(deployment["jobs"], api_client)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/dbx/commands/deploy.py", line 261, in _create_jobs
    _update_job(jobs_service, job_id, job)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/dbx/commands/deploy.py", line 286, in _update_job
    raise e
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/dbx/commands/deploy.py", line 282, in _update_job
    jobs_service.reset_job(job_id, job)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/databricks_cli/sdk/service.py", line 134, in reset_job
    return self.client.perform_query('POST', '/jobs/reset', data=_data, headers=headers, version=version)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/databricks_cli/sdk/api_client.py", line 146, in perform_query
    raise requests.exceptions.HTTPError(message, response=e.response)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://adb-111111111111.11.azuredatabricks.net/api/2.0/jobs/reset
 Response from server: 
 { 'error_code': 'INVALID_PARAMETER_VALUE',
  'message': 'Invalid python file URI: cicd_test/tasks/first/entrypoint.py. '
             'Please visit Databricks user guide for supported URI schemes.'}
```

I notice that it's the job api v2.0 in the error message, but in my ~/.databrickscfg, it's `jobs-api-version = 2.1` specified

And hereunder a part of my `deployment.json` file, it works well till dbx v0.5:

![image](https://user-images.githubusercontent.com/13083856/176399651-76ee295d-d258-4adf-bb3a-918fb8458547.png)

## Your Environment

* dbx version used: 0.6.3
* Databricks Runtime version:  10.4.x-cpu-ml-scala2.12

**Comment by renardeinside** [comment]
hi @copdips , 
since version 0.6.X all file paths need to have either `file://` or `file:fuse://` prefixes to be properly resolved. 
In your example it should look like this:

`file://cicd_test/tasks/first/entrypoint.py`

And the conf_file argument should look like:

`["--conf-file", "file://conf/testing/dev.json"]`

please read more about path adjustment in the [docs](https://dbx.readthedocs.io/en/latest/path_adjustment.html).
