### ISSUE TITLE
error when deploying package: File already exists, cannot overwrite

### ISSUE THREAD

**Issue by jaycunningham-8451** [databrickslabs/dbx#359]
## Expected Behavior

The package should deploy to Databricks without any issue.

## Current Behavior

The package deploy fails with an error:

```html
[dbx][2022-07-28 13:50:19.548] Package re-build finished
[dbx][2022-07-28 13:50:19.549] Locating package file
[dbx][2022-07-28 13:50:19.550] Package file located in: dist/jay_sample_project-0.0.1-py3-none-any.whl
[dbx][2022-07-28 13:50:19.550] Requirements file was not found
[dbx][2022-07-28 13:50:19.975] Tasks section found in the job jay-sample-project-sample-etl, job will be deployed as a multitask job
[dbx][2022-07-28 13:50:19.975] Uploading file conf/test/sample_etl_config.yml
[dbx][2022-07-28 13:50:19.975] Uploading file conf/test/sample_etl_config.yml - done
[dbx][2022-07-28 13:50:21.520] Uploading file conf/test/sample_etl_config.yml
[dbx][2022-07-28 13:50:21.520] Uploading file conf/test/sample_etl_config.yml - done
[dbx][2022-07-28 13:50:22.245] Uploading file conf/test/sample_etl_config.yml
[dbx][2022-07-28 13:50:22.245] Uploading file conf/test/sample_etl_config.yml - done
Traceback (most recent call last):
  File "/Users/j260381/.pyenv/versions/dbx-demo/bin/dbx", line 8, in <module>
    sys.exit(cli())
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/dbx/commands/deploy.py", line 178, in deploy
    adjust_job_definitions(deployment["jobs"], dependency_manager, _file_uploader, api_client)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/dbx/utils/adjuster.py", line 54, in adjust_job_definitions
    walk_content(adjustment_callback, workload_reference)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/dbx/utils/adjuster.py", line 60, in walk_content
    walk_content(func, item, content, key)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/dbx/utils/adjuster.py", line 60, in walk_content
    walk_content(func, item, content, key)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/dbx/utils/adjuster.py", line 63, in walk_content
    walk_content(func, sub_item, content, idx)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/dbx/utils/adjuster.py", line 65, in walk_content
    parent[index] = func(content)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/dbx/utils/adjuster.py", line 19, in adjustment_callback
    return adjust_path(p, file_uploader)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/dbx/utils/adjuster.py", line 93, in adjust_path
    adjusted_path = path_adjustment(candidate, file_uploader)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/dbx/utils/adjuster.py", line 79, in path_adjustment
    adjusted_path = file_uploader.upload_and_provide_path(local_path, as_fuse=fuse_flag)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/dbx/utils/file_uploader.py", line 47, in upload_and_provide_path
    self._upload_file(local_path)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/dbx/utils/file_uploader.py", line 31, in _upload_file
    mlflow.log_artifact(str(file_path), parent)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/mlflow/tracking/fluent.py", line 752, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/mlflow/tracking/client.py", line 955, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/mlflow/tracking/_tracking_service/client.py", line 365, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/mlflow/store/artifact/dbfs_artifact_repo.py", line 119, in log_artifact
    self._databricks_api_request(
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/mlflow/store/artifact/dbfs_artifact_repo.py", line 61, in _databricks_api_request
    return http_request_safe(host_creds=host_creds, endpoint=endpoint, method=method, **kwargs)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 178, in http_request_safe
    return verify_rest_response(response, endpoint)
  File "/Users/j260381/.pyenv/versions/3.9.7/envs/dbx-demo/lib/python3.9/site-packages/mlflow/utils/rest_utils.py", line 191, in verify_rest_response
    raise MlflowException("%s. Response body: '%s'" % (base_msg, response.text))
mlflow.exceptions.MlflowException: API request to endpoint /dbfs/Shared/dbx/projects/jay_sample_project/43548638b9954fb1ab462810f75559e9/artifacts/conf/test/sample_etl_config.yml failed with error code 409 != 200. Response body: '<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 409 </title>
</head>
<body>
<h2>HTTP ERROR: 409</h2>
<p>Problem accessing /dbfs/Shared/dbx/projects/jay_sample_project/43548638b9954fb1ab462810f75559e9/artifacts/conf/test/sample_etl_config.yml. Reason:
<pre>    File already exists, cannot overwrite: &apos;/Shared/dbx/projects/jay_sample_project/43548638b9954fb1ab462810f75559e9/artifacts/conf/test/sample_etl_config.yml&apos;</pre></p>
<hr />
</body>
</html>
```

## Steps to Reproduce (for bugs)

Essentially, follow the steps here: https://dbx.readthedocs.io/en/latest/templates/python_basic.html?highlight=libraries

Create a sample project like this:

```
dbx init --template=python_basic
```

and answer the questions with all the defaults, choosing (in my case) Azure as the cloud provider. Then run:

```python
dbx deploy --jobs=jay-sample-project-sample-etl --files-only
```

After the package is built, it appears to upload the same file three times (?) before failing with an error that said file already exists. 

## Context

I'm attempting to learn to use this tool properly by following the instructions. If something needs to be modified in the Python template, it's not clear what. I understand that a similar issue has been reported before and presumably addressed with "strict" path adjustment, but if that's the issue it's not clear how to enable that. I've changed the path adjustment and it failed with the same error.

## Your Environment

* dbx version used: 0.6.8
* Databricks Runtime version: 9.1.x-cpu-ml-scala2.12

**Comment by renardeinside** [comment]
hi @jaycunningham-8451 , 

I cannot reproduce this issue in any of available environments. 

Could you please verify that you have proper access to MLflow by doing the following:

- setup the MLflow tracking URI env variable:
```
export MLFLOW_TRACKING_URI=databricks://<profile-name>
```

- move to the project folder and get the experiment name:
```
cat .dbx/project.json # -> you need the `workspace_dir` value
```

- find this experiment id:

```
mlflow experiments list | grep "<experiment-name-from-previous-step>"
```

- copy the experiment ID and get the latest run per this experiment:
```
mlflow runs list --experiment-id=<experiment-id>
```

- with the value of this run, try uploading a sample file:
```
mlflow artifacts log-artifact -l conf/deployment.yml -r <run-id-from-previous-step>
```

If any of these steps fail, please write a comment to this issue.

**Comment by renardeinside** [comment]
upd. if you're using Databricks on AWS in Ohio region, it might be also relevant to [this](https://health.aws.amazon.com/health/status) incident.

**Comment by jaycunningham-8451** [comment]
> if you're using Databricks on AWS in Ohio (us-east-2) region 

Nope, we're on Azure. Ohio's right, though!

> Could you please verify that you have proper access to MLflow by doing the following:

`mlflow experiments list` fails with an error message indicating an authentication issue:

```
    raise MlflowException("%s. Response body: '%s'" % (base_msg, response.text))
mlflow.exceptions.MlflowException: API request to endpoint was successful but the response body was not in a valid JSON format. Response body: '<!doctype html><html><head><meta charset="utf-8"/><meta http-equiv="Content-Language" content="en"/><title>Databricks - Sign In</title><meta name="viewport" content="width=960"/><link rel="icon" type="image/png" href="/favicon.ico"/><meta http-equiv="content-type" content="text/html; charset=UTF8"/><link rel="icon" href="/favicon.ico"><script defer="defer" src="/login/login.bc5b5f17.js"></script></head><body class="light-mode"><uses-legacy-bootstrap><div id="login-page"></div></uses-legacy-bootstrap></body></html>'
```

The profile I've set seems to work properly in other contexts so I'm not sure why this would be the case, but I guess that means it's an MLflow issue and not a dbx issue? Funnily enough running `dbx deploy` does create the experiments successfully (you can see them in the experiments UI).

**Comment by jaycunningham-8451** [comment]
Never mind. I'm an idiot. Three cheers for me being an idiot. I configured the host incorrectly, it just always worked properly until now.
