### ISSUE TITLE
dbx not parsing git+https line in requirements.txt

### ISSUE THREAD

**Issue by filiphagan** [databrickslabs/dbx#373]
## Expected Behavior
`dbx deploy` parses all lines in requirements.txt including python dependencies to be installed directly from GitHub

## Current Behavior
Error TL;DR:
```
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'+https:/'": Expected stringEnd
```

Full logs:
```
[dbx][2022-08-08 10:57:00.249] Starting new deployment for environment dev
[dbx][2022-08-08 10:57:00.261] Using profile provided from the project file
[dbx][2022-08-08 10:57:00.264] Found auth config from provider EnvironmentVariableConfigProvider, verifying it
[dbx][2022-08-08 10:57:00.264] Found auth config from provider EnvironmentVariableConfigProvider, verification successful
[dbx][2022-08-08 10:57:02.652] Auto-discovery found deployment file conf\deployment.json
[dbx][2022-08-08 10:57:02.653] Deployment will be performed only for the following jobs: ['hello-world-job']
[dbx][2022-08-08 10:57:02.653] Re-building package
[dbx][2022-08-08 10:57:02.654] dist folder already exists, cleaning it before build
Obtaining file:///C:/some-path
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: package-name
  Building wheel for package-name (setup.py) ... done
  Created wheel for package-name: filename=package-name.whl size=1234 
  Stored in directory: C:\Users\notimportant
Successfully built package-name
[dbx][2022-08-08 10:57:18.677] Package re-build finished
[dbx][2022-08-08 10:57:18.678] Locating package file
[dbx][2022-08-08 10:57:18.679] Package file located in: dist\package-name.whl
Traceback (most recent call last):
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1654, in parseString
    raise exc
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 3205, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected stringEnd (at char 3), (line:1, col:4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\xyz\Anaconda3\envs\abc\Scripts\dbx.exe\__main__.py", line 7, in <module>
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\site-packages\dbx\commands\deploy.py", line 165, in deploy
    dependency_manager = DependencyManager(no_package, no_rebuild, requirements_file)
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\site-packages\dbx\utils\dependency_manager.py", line 26, in __init__
    self._requirements_references: List[LibraryReference] = self._get_requirements_from_file(requirements_file)
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\site-packages\dbx\utils\dependency_manager.py", line 53, in _get_requirements_from_file
    filtered_libraries = self._delete_managed_libraries(requirements_content)
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\site-packages\dbx\utils\dependency_manager.py", line 32, in _delete_managed_libraries
    for package in packages:
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\site-packages\pkg_resources\__init__.py", line 3089, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "C:\Users\xyz\Anaconda3\envs\abc\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 104, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'+https:/'": Expected stringEnd
```

## Steps to Reproduce (for bugs)
1. Add `git+https://...` line in `requirements.txt`
2. Create proper exemplary job
3. Run `dbx deploy --job=hello-world-job -e dev` 

Example:
```
package-one==1.0
# Some comment
git+https://github.com/path/to/package-two@41b95ec#egg=package-two
```
## Your Environment
* dbx version used: 0.6.10

**Comment by renardeinside** [comment]
hi @filiphagan , 
support for `--requirements-file` is deprecated. Please use the `setup.py` based approach as described [here](https://stackoverflow.com/questions/32688688/how-to-write-setup-py-to-include-a-git-repository-as-a-dependency):
```
# setup.py contents

setup(
    ...
    install_requires = [
        'some-pkg @ git+ssh://git@github.com/someorgname/pkg-repo-name@v1.1#egg=some-pkg',
    ]
)
```

**Comment by filiphagan** [comment]
Hi Ivan, thank you for your support. I'll try this way

**Comment by filiphagan** [comment]
@renardeinside I'm sorry for the confusion, I didn't describe the issue correctly. We do have also a `setup.py` in our repository that parses all the requirements from requirements*.txt files and then calls `setup()` including `install_requires` argument like above
