### ISSUE TITLE
[Bug or Doc Issue] dbx fails execute python task when no task parameters provided

### ISSUE THREAD

**Issue by danpicton** [databrickslabs/dbx#383]
## Expected Behavior

`dbx execute --cluster-id=<running_AP_cluster_id> --job=dbx-demo-job --no-rebuild --no-package` will successfully complete and show the results as described in [tutorial](https://docs.databricks.com/dev-tools/dbx.html#create-a-minimal-dbx-project-for-python).

## Current Behavior

Running the above command fails with the following:
```
[dbx][2022-08-12 08:42:37.176] Using profile provided from the project file
[dbx][2022-08-12 08:42:37.182] Found auth config from provider ProfileEnvConfigProvider, verifying it
[dbx][2022-08-12 08:42:37.183] Found auth config from provider ProfileEnvConfigProvider, verification successful
[dbx][2022-08-12 08:42:37.183] Profile DEFAULT will be used for deployment
[dbx][2022-08-12 08:42:38.812] Executing job: dbx-demo-job in environment default on cluster None (id: <redacted>)
[dbx][2022-08-12 08:42:38.812] No rebuild will be done, please ensure that the package distribution is in dist folder
[dbx][2022-08-12 08:42:38.814] Auto-discovery found deployment file conf/deployment.yaml
[dbx][2022-08-12 08:42:38.825] Preparing interactive cluster to accept jobs
[dbx][2022-08-12 08:42:38.854] Cluster is ready
[dbx][2022-08-12 08:42:38.855] Preparing execution context
[dbx][2022-08-12 08:42:39.184] Existing context is active, using it
[dbx][2022-08-12 08:42:39.479] Processing task parameters: None
Traceback (most recent call last):
  File "/usr/local/bin/dbx", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dbx/commands/execute.py", line 151, in execute
    controller_instance.run()
  File "/usr/local/lib/python3.8/site-packages/dbx/api/execute.py", line 54, in run
    self.preprocess_task_parameters(self._task.spark_python_task.parameters)
  File "/usr/local/lib/python3.8/site-packages/dbx/api/execute.py", line 90, in preprocess_task_parameters
    walk_content(adjustment_callback, parameters)
  File "/usr/local/lib/python3.8/site-packages/dbx/utils/adjuster.py", line 65, in walk_content
    parent[index] = func(content)
```

## Steps to Reproduce (for bugs)

1. Install vscode with Remote-Containers extension
2. Open folder as container using Debian Bullseye (Python) 3.8 image
3. Follow [tutorial](https://docs.databricks.com/dev-tools/dbx.html#create-a-minimal-dbx-project-for-python), run command

I've also attempted to follow the instructions on the host Mac, across different Python versions, within and out of a virtual environment. The error I'm receiving is consistent with that I'm getting from the container.

## Context

Contents of `.dba/project.json`:

```
{
    "environments": {
        "default": {
            "profile": "DEFAULT",
            "workspace_dir": "/Shared/dbx/projects/dbx1",
            "artifact_location": "dbfs:/dbx/dbx1"
        }
    }
}
```

Contents of `conf/deployment.yaml`:

```
environments:
  default:
    jobs:
      - name: "dbx-demo-job"
        spark_python_task:
          python_file: "file://dbx-demo-job.py"
```

In `dbx/commands/execute.py`, `job_payload` (line #112):

```
{'name': 'dbx-demo-job', 'spark_python_task': {'python_file': 'file://dbx-demo-job.py'}}
```

When `SparkPythonTask` is created, no parameters are provided, so ends up with the following:

```
SparkPythonTask(python_file=PosixPath('dbx-demo-job.py'), parameters=None)
```

## Fix/Correction

Adding an empty parameter list to `conf/deployment.yaml` allows the task to execute successfully:

```
environments:
  default:
    jobs:
      - name: "dbx-demo-job"
        spark_python_task:
          python_file: "file://dbx-demo-job.py"
          parameters: []
```

Correcting this behaviour would require `SparkPythonTask.parameters` to default to an empty list if none are provided. Otherwise, a documentation update would be useful :)

Results of `dbx execute --cluster-id=<redacted> --job=dbx-demo-job --no-rebuild --no-package`:

```
[dbx][2022-08-12 09:40:56.055] Using profile provided from the project file
[dbx][2022-08-12 09:40:56.061] Found auth config from provider ProfileEnvConfigProvider, verifying it
[dbx][2022-08-12 09:40:56.061] Found auth config from provider ProfileEnvConfigProvider, verification successful
[dbx][2022-08-12 09:40:56.061] Profile DEFAULT will be used for deployment
[dbx][2022-08-12 09:40:56.852] Executing job: dbx-demo-job in environment default on cluster None (id: <redacted>)
[dbx][2022-08-12 09:40:56.852] No rebuild will be done, please ensure that the package distribution is in dist folder
[dbx][2022-08-12 09:40:56.855] Auto-discovery found deployment file conf/deployment.yaml
[dbx][2022-08-12 09:40:56.863] Preparing interactive cluster to accept jobs
[dbx][2022-08-12 09:40:56.892] Cluster is ready
[dbx][2022-08-12 09:40:56.894] Preparing execution context
[dbx][2022-08-12 09:40:57.060] Existing context is active, using it
[dbx][2022-08-12 09:40:57.318] Processing task parameters: []
[dbx][2022-08-12 09:40:58.304] Processing task parameters - done
[dbx][2022-08-12 09:40:58.304] Starting entrypoint file execution
[dbx][2022-08-12 09:41:09.846] Command successfully executed
+-----------+----------+---------+--------+
|AirportCode|      Date|TempHighF|TempLowF|
+-----------+----------+---------+--------+
|        PDX|2021-04-03|       64|      45|
|        PDX|2021-04-02|       61|      41|
|        SEA|2021-04-03|       57|      43|
|        SEA|2021-04-02|       54|      39|
+-----------+----------+---------+--------+

Out[2]: DataFrame[]
[dbx][2022-08-12 09:41:09.847] Command execution finished
```

## Your Environment

- MacOS 12.5 Monterey 
- vscode with Remote-Containers extension
- Container running Debian Bullseye with Python 3.8.13

* dbx version used: DataBricks eXtensions aka dbx, version ~> 0.6.11
* Databricks Runtime version: 10.4 LTS

**Comment by renardeinside** [comment]
hi @danpicton , 
thanks a lot for reporting the issue, I'll take care of it

**Comment by danpicton** [comment]
If it saves time, I was able to fix the code by changing `dbx/model/task.py` line 21 to:

```
parameters: Optional[List[str]] = []
```

The `PythonWheelTask` class also has `Optional` params (line 16), so not sure if the issue would occur there also.
