### ISSUE TITLE
typing_extensions 4.6.0 causes pydantic issues

### ISSUE THREAD

**Issue by Stklingner** [databrickslabs/dbx#785]
## Expected Behavior
N/A

## Current Behavior
Non-zero exit code on initialisation

## Steps to Reproduce (for bugs)
Attempt to deploy while using typing_extensions > 4.5.0

## Context
Automated build to existing workflow environment

## Your Environment
Github Actions: Ubuntu 22.04
Python 3.9.5
* dbx version used: 0.18.14
* Databricks Runtime version: 2.1

## Error log
```
Run export DATABRICKS_JOBS_API_VERSION=2.1
  export DATABRICKS_JOBS_API_VERSION=2.1
  dbx deploy --deployment-file conf/******.yml --environment ***
  shell: /usr/bin/bash -e {0}
  env:
    DATABRICKS_HOST: ***
    DATABRICKS_TOKEN: ***
    AWS_DEFAULT_REGION: ***
    AWS_REGION: ***
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    pythonLocation: /opt/hostedtoolcache/Python/3.9.5/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.5/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.5/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.5/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.5/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.5/x64/lib
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.5/x64/bin/dbx", line 5, in <module>
    from dbx.cli import entrypoint
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/dbx/cli.py", line 7, in <module>
    from dbx.commands.deploy import deploy
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/dbx/commands/deploy.py", line 8, in <module>
    from dbx.api.adjuster.adjuster import AdditionalLibrariesProvider, Adjuster
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/dbx/api/adjuster/adjuster.py", line 6, in <module>
    from dbx.api.adjuster.mixins.existing_cluster import ExistingClusterAdjuster
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/dbx/api/adjuster/mixins/existing_cluster.py", line 8, in <module>
    from dbx.models.workflow.v2dot0.workflow import Workflow as V2dot0Workflow
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/dbx/models/workflow/v2dot0/workflow.py", line 19, in <module>
    class Workflow(WorkflowBase, TaskMixin, AccessControlMixin):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/typing.py", line 835, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
Error: Process completed with exit code 1.
```

**Comment by Stklingner** [comment]
Probably not really a dbx issue so feel free to close at your discretion.

**Comment by camilo-s** [comment]
I'm facing the same issue although I found issue #756  first.

**Comment by Stklingner** [comment]
Setting typing_extensions==4.5.0 in our project requirements.txt was our quick fix for others who have urgent deployments; no side-effects noticed.

**Comment by giovannipapini-agilelab** [comment]
> Setting typing_extensions==4.5.0 in our project requirements.txt was our quick fix for others who have urgent deployments; no side-effects noticed.

Same issue here, this solution works correctly also for us.

**Comment by mikeweltevrede** [comment]
> Setting typing_extensions==4.5.0 in our project requirements.txt was our quick fix for others who have urgent deployments; no side-effects noticed.

This helped for me as well. Seems to come from the `rich` library, [which specifies](https://github.com/Textualize/rich/blob/master/poetry.lock#LL61C11-L61C11) `typing-extensions>=3.10.0.0`. The new `typing-extensions` [release 4.6.0 of 13 hours ago](https://pypi.org/project/typing-extensions/#history) then causes this issue.

**Comment by renardeinside** [comment]
hi everyone on this thread, 
first of all thanks a lot for reporting the issue.

I've explicitly fixed pydantic version to a compatible one in dbx 0.8.16. 
Please check it with the latest version, and feel free to reopen the request if it pops up again.
