### ISSUE TITLE
Failing step due to a Pydantic issue when running `dbx configure --enable-inplace-jinja-support`

### ISSUE THREAD

**Issue by mikeweltevrede** [databrickslabs/dbx#809]
## Expected Behavior
Passing step in CI/CD pipeline to configure dbx to enable Jinja support.

## Current Behavior
Failing step due to a Pydantic issue when running `dbx configure --enable-inplace-jinja-support` in CI/CD pipeline.

Notice that the pipeline has the following dependency for Pydantic (2.0 released on June 30, 2023):

```
Collecting pydantic<=2.0.0,>=1.9.1 (from dbx==0.8.12)
  Downloading pydantic-2.0-py3-none-any.whl (355 kB)
```

## Steps to Reproduce (for bugs)
Install `dbx==0.8.12` and set up a pipeline that runs `dbx configure --enable-inplace-jinja-support`.

## Your Environment

* dbx version used: 0.8.12
* Databricks Runtime version: 12.2 LTS ML (although this happens before deploy and launch.

Traceback:
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.17/x64/bin/dbx", line 5, in <module>
    from dbx.cli import entrypoint
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/dbx/cli.py", line 7, in <module>
    from dbx.commands.deploy import deploy
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/dbx/commands/deploy.py", line 8, in <module>
    from dbx.api.adjuster.adjuster import AdditionalLibrariesProvider, Adjuster
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/dbx/api/adjuster/adjuster.py", line 6, in <module>
    from dbx.api.adjuster.mixins.existing_cluster import ExistingClusterAdjuster
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/dbx/api/adjuster/mixins/existing_cluster.py", line 8, in <module>
    from dbx.models.workflow.v2dot0.workflow import Workflow as V2dot0Workflow
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/dbx/models/workflow/v2dot0/workflow.py", line 8, in <module>
    from dbx.models.workflow.common.new_cluster import NewCluster
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/dbx/models/workflow/common/new_cluster.py", line 8, in <module>
    class AutoScale(FlexibleModel):
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/dbx/models/workflow/common/new_cluster.py", line 12, in AutoScale
    @root_validator()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.0/u/root-validator-pre-skip
```

**Comment by mikeweltevrede** [comment]
Solution: upgrade dbx to > 0.8.16
