### ISSUE TITLE
dbx not working with pydantic 2.0 (default) requires 1.10

### ISSUE THREAD

**Issue by geiranton** [databrickslabs/dbx#810]
## Steps to Reproduce (for bugs)
in clean environment:
pip install dbx
dbx

Traceback (most recent call last):
  File "/usr/local/bin/dbx", line 5, in <module>
    from dbx.cli import entrypoint
  File "/usr/local/lib/python3.10/site-packages/dbx/cli.py", line 7, in <module>
    from dbx.commands.deploy import deploy
  File "/usr/local/lib/python3.10/site-packages/dbx/commands/deploy.py", line 8, in <module>
    from dbx.api.adjuster.adjuster import AdditionalLibrariesProvider, Adjuster
  File "/usr/local/lib/python3.10/site-packages/dbx/api/adjuster/adjuster.py", line 6, in <module>
    from dbx.api.adjuster.mixins.existing_cluster import ExistingClusterAdjuster
  File "/usr/local/lib/python3.10/site-packages/dbx/api/adjuster/mixins/existing_cluster.py", line 8, in <module>
    from dbx.models.workflow.v2dot0.workflow import Workflow as V2dot0Workflow
  File "/usr/local/lib/python3.10/site-packages/dbx/models/workflow/v2dot0/workflow.py", line 8, in <module>
    from dbx.models.workflow.common.new_cluster import NewCluster
  File "/usr/local/lib/python3.10/site-packages/dbx/models/workflow/common/new_cluster.py", line 8, in <module>
    class AutoScale(FlexibleModel):
  File "/usr/local/lib/python3.10/site-packages/dbx/models/workflow/common/new_cluster.py", line 12, in AutoScale
    @root_validator()
  File "/usr/local/lib/python3.10/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.
## Your Environment
python9 og python 10
* dbx version used:
* 0.8.17
* Databricks Runtime version: 

## FIxed with pip install pydantic==1.10.10

**Comment by followingell** [comment]
+1

We also saw this behaviour _(thanks for listing the fix @geiranton)_.

**Comment by geiranton** [comment]
Seems to have version requirements in setup.py (does it work?), but still fails in a clean docker python:3.9 and python:3.10

**Comment by geiranton** [comment]
0.8.17 is fine
pydantic==1.10.10
└── dbx==0.8.17 [requires: pydantic>=1.10.8,<2.0.0]

**Comment by geiranton** [comment]
0.8.17 is fine
pydantic==1.10.10
└── dbx==0.8.17 [requires: pydantic>=1.10.8,<2.0.0]
